name: lambda_cli
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/lambdal/lambda-cloud-dart-cli
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  openapi:
    path: api
  openapi_generator_annotations: ^6.1.0
  args: ^2.6.0
  cli_table: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.14
  lints: ^5.0.0
  openapi_generator: ^6.1.0
  test: ^1.24.0
